### ISSUE TITLE
Receive 403 when getting session token 

### ISSUE THREAD

**Issue by hkhik-ops** [morsisko/NosTale-Auth#6]
The solution is once my computer restart, I use the example script will return cannot obtain token. But after I turn on the GFClient, it back to normal. 

Can I get the session token without the GFClient ?

**Comment by morsisko** [comment]
Hello yes, you need to send one more packet so the server thinks you are using gf launcher, I will update this repository in free time (soon).

**Comment by hkhik-ops** [comment]
> Hello yes, you need to send one more packet so the server thinks you are using gf launcher, I will update this repository in free time (soon).

Oh ok.. thanks anyway

**Comment by hkhik-ops** [comment]
May I know when will the new version release ?

**Comment by hkhik-ops** [comment]
> Hello yes, you need to send one more packet so the server thinks you are using gf launcher, I will update this repository in free time (soon).

It's send a api or connect the socket ?

**Comment by morsisko** [comment]
It should work now, the package has been updated

**Comment by DownD** [comment]
Hi, i'm still not able to get the token, after checking packets sent by oficial GF client, i found tou that there is a new field called blackbox that might be the cause of it.
Check out the packet which get's the session:
`URL: https://spark.gameforge.com/api/v1/auth/thin/codes

Headers:
{
tnt-installation-id : c5a2be23-db08-4696-9fd6-7f916f40dc50
Content-Type : application/json
Authorization : Bearer c4249148-6f9f-4db8-a1bf-8e5dbce2b6e7
User-Agent : Chrome/C2.1.22.784 (1dd21dea74) GameforgeClient/2.1.22
}
{ "blackbox":"0400fJygH18RWyQpIfq2LLtL%2FSbD8aL0iJbSB73Gzb7UzVsCP3I%2FgtJSIJV5spq18yMggZ089ijsOwoOFw%2BA%2BCal0trP0YZkcILYulZb7T%2BP6Dnk6vjoZkJHkUfc4u0zUm2wZOY6osDdKdEFr4MiRhDOrAL7lfDStBt%2FEARLsaYQADm1ZI66QifbWfNr%2FffQjx32cHM4ZAzgnG%2FxVajijX%2FolO13wFOzF3vcASEh9EGzqDn0ebNMdBWQC%2B5lwoUK2WuBLtZ3%2BSDgXZw6vHRehvqZuSO16m37UUIe%2Fpr71oD561qOd9AmjPBIJ7w5QDLm19G3el0yeMn80LBOfdJx%2BsF9hAWvgyJGEM6sAvuV8NK0G38QBEuxphAAObVkjrpCJ9tZ82v999CPHfZwczhkDOCcb%2B9RJsn4u3PdHf7WUtiodkQnjn8B4Ycpmk6wotuMa3QQpWnhYhSTkGZv47mN%2BmlXbz5ydHtJgfIvAtidd%2Br4Je%2BDbdw3OA3thNam8c9e8d0cB2jYNAlzCL%2FUasOfo40YvJN4gIkzMkSDol8MV62NJChlBzOEDZAORh%2BZZSmvtxitk0ZmZUd7ml32yZYx20HX1pF%2FjNlMMT59ijFVy3r9MDLA9wKgREKKIy8m9boaH7hGcap7OmtqW0C3FDFrQJyxWsfIto3Z69Xn5DQkjMJvH09mXhYVGbPcmoJ5T7Yek9EEelK1o%2BP3Gqltlan%2Fk0WyHYZvf36WupUO7WxGgUnAs36S43ukeU1P5T0YLXuOWeFzAIsjF5E9P9iPBk6gRUU9pqnHrD%2BvTEzvgriaMoAypQuyPr0t8ztVFisjUV4dJsOyBOIeMU7SprhI185O%2ByC2f3lLEO0Tay66NZEyiLNePemJKSIdwO9O5ZtntuUkG6NTg7HBwwXdkjno7JO4wb%2BQwpaHbSQQp9Xb5mNV6QxgbclGASpJ6ETmLbtOxKYkBFXNzD8GfSEP7Qs%2FyoVIBnjaisB2n%2FX%2FDCQnfv7tOhDqP1BGJ%2FRBTEX78VYLhnQo%2BZYXzS%2BwIvjs49bt3pcwrl2BAPrJz%2FfklocMaR4LlIcIcs8hIqKrjK%2Bgd9fidlHjZD64xKZFk5ZzIuZC31uyK4wyHL9MOnRTMthLIs6dvMfuh6DgklNKGT1jRHxfYV3WeA0UPPK1E1%2BGGd9pLLGVQUKIYR2wTw53CiWK%2FXQXiHK5P5nmJq7OBsHVc7I%2BvS3zO1UWKyNRXh0mw7IE4h4xTtKmuEjXzk77ILZ%2FeUsQ7RNrLro1kTKIs1496YkpIh3A707lm2e25SQbo1ODscHDBd2SOejsk7jBv5DClodtJBCn1dvmY1XpDGBtyWF8hRwW7Jsss29L0sFkQPmgeU0nMUZl7EsgFfeTU6F2zaadiCX%2Bz7uNc557XJoPF7zxBTr1PcxXCNSZFyAesEZzMX4o5g8yeD3ntbZGTwYI469ZjvEUHTwK5Y1p3C%2BnEP2asQzLZ6w4E2lz2hplSqYzkaSFKYawdY7zP8Fwulf0PscIqwcXsJ0RbDa0few3jojCIs6CJKS8yERuvb4dUKNDmdN5bP9mpnR27OTphfvURV8flS7U9rr3CrKYtvroUvtrit541f9WpXlOsoW2jK%2BYY4NdZuSstHfEF80%2BAcQH38pSyICgJR0md2Sb2hs%2BsshkEYRNxvMXQ5awiasnbER0fyuOn55BAY5HS7LHY9ZOx3wnvsytPEtVIPeuIv03NGBbdh0Bb%2FNesakRVXRQbxyhkyYA7cEX4FmLG8C0BgAMgCi%2FIUYfrFnO2C2QhfcrYKw0A4A1FEIr%2BirbEg1FBieQCxk6EfY3GOreue2jWdfsxRojPHmqsAd1trVeymGwQD6X6lAuw1GESVlWegYtjXG2varwhLUcmkcGtA77ZQbLUhz1EbmUqLuSLJoZYGfqlamhJTVCr5rSVXvGSUaueuIOcNcPNrnNIn4ECK4affZeVhAf2vXJLQUA%2FG%2Br8ivKqlCN%2BF5ItSoAINV%2Bte71zsxAvp7DNvkGIa%2BEQsHLHekzilavPC84y%2FaINe5RYPCTuw4z4G10EhjpjAfLtXiq7ysEXVgwvaq5%2BDNbvRYwMAhMdBVJnaWFT6bHIxx%2FokTmwpl2LrfPpgqXDArTBfvTOqG3rOeWMyMoaGPOc8QZfwM7TF%2FzYvtRAMrvsD8Ae2HMhB4VuAIQCVKUyf9Hcx0xPjGFX87thlCpihnHqo7lo7Rw6xSE25pgt8d9kQzOGQU%2BQOpJ3bVNobT8%2Bkd%2Bd4C9ySyUQH6KVWu0jYt6rz3%2BadAk%2FPT2ujhoXqbWfvi2lw6riN3KAK3HfHfuEBjstYcgdPgboKyvsZGvQpJQWQZWW45YmhWrcp6UYq7TH0xXuFNxJhdDi0Is2uEJtpLdIKEZY5vyqs5CWF8R9ej1v8GpePsDB3jfxzbrrvijixQ7S8m22w6IPq3Y8odELrmI8fbS6%2F4zJHwVUpAL3hHYz83jBQ9UNzgxO8skMV1TM%2B276GxRfLnYpgrFwByeZL3ZPYDOD4VV3oN0GlJPfTKXk5XFKpfKFwMziOgSCldnPF5iSWutdYGaxWUyPazpLrR5qVfbWTGfTsVbXQT0DN6L7b%2FjBRV40FED%2BOJV8JvhPWeK34u0kpPpgRsTFvPqxLT6%2FgNWn%2BdqWxlmVPBntYt4I2N0m4zpoYb0K5YE94ld4nDHwtcX5q07RSeLq6w7SOPwywIOEa6E3GxuGh%2BZwJX%2BLZ3rHuH%2FTt97FZO0RPc%3D%3B0400QTsLRMZN1JMpIfq2LLtL%2FSbD7aL0iJbSB73Gzb7UzVsCP3I%2FgtJSIJV5spq18yMg1w37HssRrCnp4KidVdtXi4eX4FQvHSZ0dynhDuaeEoXRKCTo5nE4c7eCdLAVT2eVYg8CuMOt5MJPjdHmP6jzDq76TEQWHVtPC67c8HHFZGXvUSbJ%2BLtz3R3%2B1lLYqHZEJ45%2FAeGHKZpOsKLbjGt0EKVp4WIUk5Bmb%2BO5jfppV28%2BcnR7SYHyLwLYnXfq%2BCXvg23cNzgN7YTWpvHPXvHdHAdo2DQJcwi%2F1GrDn6ONGLyTeICJMzJEg6JfDFetjSQoZQczhA2QDkYfmWUpr7cYrZNGZmVHe5pd9smWMdtB19aRf4zZTDE%2BfYoxVct6%2FTAywPcCoERCiiMvJvW6Gh%2B4RnGqezpraltA%2BcY72jOZIF2EHWRZfJYszMIHlRUZufUhTL9Hw1MH2EjEsMs6T9E4jZWDPrACqg%2FWREplruLsbiDYAMZZ%2FWFRhVOkseiJdXPrs0Jvt6oQ%2FZL%2FPC9sqCDmr84hwN7eK4ojpKL6pKP30poE5T44dGCHQHAGyIcPoBlegsyCuk4gTJx7HVMsBHJtSvhfflTR5XM9lcABhHdx%2BC%2F%2FUv35HZUyMeTQHjy7H5XhLHCHAGY3J0jpLqVrSVzsI1LB6M5fl2EoMEAoEitEttFUo1DRkUtPGPYtb5lwVUYp0%2BAOKxv8aAJ4VShbY%2BEVBM19ITN7QCcbWrjg3IZNlqx9izplUCi1Hah1fJQrFSBW1n74tpcOq4gNfyJw5Y9lzLhejolH6jy42HYF5oyZHJcyjhwX26aZSnUtib%2Fl7Jtu1zsSNofWZ2k4Q2BjiRVT3AHzj486sjgySgPiIcnlrVAJuvK70bwBpPIsAANkjj%2F29bxO3t%2FtHyarRICnXBfM%2BncZzhIqXLWnEMCy0s3hRLn08Th9FlNHDPbKRXey06cY4a7euFqiMUgzqbwpmWa8I1vBrV9Y5J00%2BF9%2BVNHlcz2VwAGEd3H4L%2F9S%2FfkdlTIx5NAePLsfleEscIcAZjcnSOkupWtJXOwjUsHozl%2BXYSgwQCgSK0S20VSjUNGRS08Y9i1vmXBVRinT4A4rG%2FxoAnhVKFtj4RUEN0wvpmFXnIR%2BhuI6Fw40k82cGDz2TnqsW6E5T7SjbTuqBCdF6UcylrGAqHKF92svMyIXqubL0y1a%2B8GxQj%2BMNnM2StpuO2qITJkQZqVZ%2BNDDnr3zZMprhFlMDFylXpa%2BX0ZX3CC4WKT0g4cDc2kq2jqWZvjqZtyKyzR7%2B%2BNeG1pe0Z7JXJouIkAIJ17BA4mgC3reTMw%2FsNbp%2FnRCO0LRUFb%2BdMkyvY6499mLYqzQSDmlXg5WnOMzQdUWD9TFBPL0yf%2FUVUCbkSalMMek4lUjcted%2Btrm4ecPjZ9ET08wP5CoqUAig7loOegjfA99Is%2FnDMZHptbM%2FJEKVwi5Vf2K7odMpSRnzNZulI6aPXTMa2hFcUixHRqPguMya12GLdG7O8xzyZZyces4cd3X0jzFPm%2Fkce6S7PuTGYWc8AmavPBwAo%2BULV61ku9LS%2FpQctkHj3c0txsHKYeB8StWeCEUHWJhJoe6PuBOLzuv2xN%2FczR1orTsvXNgm7n%2FsWxn7%2FH5AW2%2Bg45RRhYTd7iBDQXwlolwfhv3T%2FL8nlHTG4hddW9YcOZUVgXXtW4WFNWvQdbwyXMc8jUd%2BsbKDJat%2BwVCEuCmxH92r4zdbe1ooBUjJwNaO8BHRuzV7QpNxM%2BtnOGFoB6GlplicbneqIEVQz0l0%2B2pG8r1E8FAQnC3Aap259u%2Fr%2FavAI4CgshGmmLnmF33xg%2BTMo1D9KdADIdYkkbFwnDAmwrXL24zmQYH8J11RAgj6pOAEUxLS82l3RxnVTS8Bn6UPppbpEx2yI4NUevtFI3VWslHIA1HlxpJdxZsTiA8SNSjt3IUeI8pb%2Bx26JQT54oHUQg194VJ7Rrl00Uhlk8Tq5E5uP%2BEF9mRDcWAtKqkKiyZm5DpIYom1lN8D%2BV7%2B4I8UlBcTcjVU24m1K5%2FEVm1JKfmM4dz0BIFCdJS%2BUWAwdremPikMfQVk%2F5Xex5l%2BWBAy7%2BSS69LNHXzsmKZcrh%2BWSBv7N11dPUNbNwRBYgdo5ZTafQ2K6eGKHhIVZ%2BkL0TUIeJSX2jvCNLLkECN938BIhQU70Gs9clcBt2CuXqPMs4m4iyx8biEhxaZ0bQWF%2BLYodEQqSSz4D2oX8xddPVLREXyr6g1MGvZTGoZ0R%2B%2BgZDxqyp5Qg3Ihc9rIWJddde8AJQzGWQJrkoq6WqiqpT%2FZ2os8cftZnE52tsQ3akWf6Vjmet7Izx9a0pwtxlhyxr%2BMSuYCzV4EeXWkSCrd%2B8hWNe8t8yxlr6Ubj8hZ4E%2FmyVI15keDmv9Cz54ocMwKxpYzkpySHJh0iGl0SF2GHfOoLiOk6hxwW6LGEvv1E4tnVDncDqYA7EuozgWn1mq%2F6yCKHopGiHr3UU2r8RcoMzw2dFoJS2e0p17JUA%2FMzXaLUIVZA3VCDN2VD1nzpaJhFnlRUsAIH8MkWqe%2BqHqbw%2B0qboxRtV7WojxyUuXFj0JkRr8lr%2Fn6wvyxc1KnErkmUJqbhmNtIi4ZjpK%2BPRxtpMlRXos37aMOxV2mJYh8UXcGQ65LwYi19KkUfbUypfCSe%2FThHqTfHmHBIAKgh4kI7W0FwpNDpwR7rzwzWyySyItDQtZAKXRWCLggWkttbzfedGB0M4GfixARSQGRYsY04SbT97kXj8%2FWV%2FuzB68grIDg6dNYoAUVA%3D%3D",
    "platformGameAccountId":"1dXXd2b8-bc7b-4bcb-b3f1-a2dd2d1fa345"
}`

I have no clue to what is this "blackbox".

**Comment by morsisko** [comment]
For me it works great without the blackbox.

**Comment by DownD** [comment]
I managed to get it now, i was using an account from metin2, it seems like this technique only work with NosTale accounts, when using other type of game account it gets denied.

**Comment by morsisko** [comment]
Maybe I will look into the blackbox thing in free time, anyway the repository is focused more towards nostale, and at the moment nostale doesn't require that parameter.
